const markets=[
{symbol:'BTC/USDT',name:'Bitcoin',icon:'₿',price:77282.09,change:0.12,high:78424.15,low:75884.4,type:'crypto',bg:'#f7931a'},
{symbol:'ETH/USDT',name:'Ethereum',icon:'◆',price:2391.09,change:-0.98,high:2440.55,low:2362.3,type:'crypto',bg:'#627eea'},
{symbol:'XAU/USDT',name:'Gold',icon:'Au',price:4388.21,change:1.38,high:4404.61,low:4308.2,type:'metal',bg:'#b98a11'},
{symbol:'XAG/USDT',name:'Silver',icon:'Ag',price:65.3289,change:1.94,high:66.05,low:63.81,type:'metal',bg:'#a6a8ac'},
{symbol:'XRP/USDT',name:'XRP',icon:'X',price:1.3469,change:-0.08,high:1.3821,low:1.319,type:'crypto',bg:'#111'},
{symbol:'LTC/USDT',name:'Litecoin',icon:'Ł',price:49.67,change:0.06,high:50.21,low:48.83,type:'crypto',bg:'#345d9d'},
{symbol:'BNB/USDT',name:'BNB',icon:'◇',price:687.56,change:1.04,high:694.44,low:674.11,type:'crypto',bg:'#c99b14'},
{symbol:'SOL/USDT',name:'Solana',icon:'S',price:99.55,change:0.08,high:101.1,low:97.2,type:'crypto',bg:'#6d4cd8'},
{symbol:'DOGE/USDT',name:'Dogecoin',icon:'Ð',price:.08155,change:.03,high:.0829,low:.0798,type:'crypto',bg:'#9f842c'},
{symbol:'TRX/USDT',name:'TRON',icon:'T',price:.3248,change:.49,high:.3272,low:.3201,type:'crypto',bg:'#d71920'}
];
let currentMarket=markets[0],direction='up',duration=60,balance=12345.67,totalPledged=12500,activeTrades=[],selectedPledge={product:'Flexible',min:100};
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const fmt=(n,d=2)=>Number(n).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
function decimals(v){return v<1?6:v<100?4:2}
function renderMarkets(filter='all'){const list=$('#market-list');list.innerHTML='';markets.filter(m=>filter==='all'||m.type===filter).forEach(m=>{const row=document.createElement('div');row.className='market-row';row.innerHTML=`<div class="market-name"><span class="coin-icon small" style="background:${m.bg}">${m.icon}</span><div><strong>${m.symbol}</strong><small class="muted" style="display:block;margin-top:3px">${m.name}</small></div></div><strong>${fmt(m.price,decimals(m.price))}</strong><strong class="${m.change>=0?'positive':'negative'}">${m.change>=0?'+':''}${m.change.toFixed(2)}%</strong><span>${fmt(m.high,decimals(m.high))}</span><button>Trade</button>`;row.querySelector('button').onclick=()=>{selectMarket(m);navigate('trade')};list.appendChild(row)})}
function selectMarket(m){currentMarket=m;$('#trade-symbol').textContent=m.symbol;$('#trade-name').textContent=m.name;$('#trade-icon').textContent=m.icon;$('#trade-icon').style.background=m.bg;$('#trade-price').textContent=fmt(m.price,decimals(m.price));$('#trade-change').textContent=`${m.change>=0?'+':''}${m.change.toFixed(2)}%`;$('#trade-change').className=m.change>=0?'positive':'negative';$('#trade-high').textContent=fmt(m.high,decimals(m.high));$('#trade-low').textContent=fmt(m.low,decimals(m.low));$('#chart-price-badge').textContent=fmt(m.price,decimals(m.price));drawChart()}
function navigate(name){$$('.page').forEach(p=>p.classList.remove('active'));const page=$(`#page-${name}`);if(page)page.classList.add('active');$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));window.scrollTo({top:0,behavior:'smooth'});if(name==='trade')setTimeout(drawChart,30)}
$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>navigate(b.dataset.nav)));$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderMarkets(b.dataset.filter)});
function updatePotential(){const amount=Number($('#trade-amount').value)||0;$('#potential-return').textContent=`${fmt(amount*1.82)} USDT`}$('#trade-amount').addEventListener('input',updatePotential);$$('[data-amount]').forEach(b=>b.onclick=()=>{$('#trade-amount').value=b.dataset.amount;updatePotential()});
$('#up-btn').onclick=()=>{direction='up';$('#up-btn').classList.add('active');$('#down-btn').classList.remove('active')};$('#down-btn').onclick=()=>{direction='down';$('#down-btn').classList.add('active');$('#up-btn').classList.remove('active')};$$('[data-duration]').forEach(b=>b.onclick=()=>{duration=Number(b.dataset.duration);$$('[data-duration]').forEach(x=>x.classList.remove('active'));b.classList.add('active')});
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2600)}
$('#place-trade').onclick=()=>{const amount=Number($('#trade-amount').value);if(!amount||amount<10)return showToast('Minimum demo trade is 10 USDT.');if(amount>balance)return showToast('Insufficient demo balance.');balance-=amount;activeTrades.push({id:Date.now(),market:currentMarket,dir:direction,entry:currentMarket.price,amount,end:Date.now()+duration*1000});updateBalances();renderPositions();showToast(`${direction==='up'?'Up':'Down'} demo trade opened on ${currentMarket.symbol}.`)};
function renderPositions(){const list=$('#positions-list');if(!activeTrades.length){list.className='positions-list empty-state';list.textContent='No active trades yet.';return}list.className='positions-list';list.innerHTML=activeTrades.map(t=>{const left=Math.max(0,Math.ceil((t.end-Date.now())/1000));return `<div class="position-row"><strong>${t.market.symbol}</strong><span class="${t.dir==='up'?'positive':'negative'}">${t.dir==='up'?'↑ Up':'↓ Down'}</span><strong>${fmt(t.entry,decimals(t.entry))}</strong><span>${fmt(t.amount)} USDT</span><span>${left}s</span><span>Active</span></div>`}).join('')}
function updateBalances(){$('#available-balance').textContent=`${fmt(balance)} USDT`;$('#asset-available').textContent=fmt(balance);$('#asset-pledged').textContent=fmt(totalPledged);$('#total-pledged').textContent=`${fmt(totalPledged)} USDT`}
setInterval(()=>{markets.forEach(m=>{const move=(Math.random()-.5)*.0012;m.price=Math.max(.000001,m.price*(1+move));m.high=Math.max(m.high,m.price);m.low=Math.min(m.low,m.price)});if($('#page-markets').classList.contains('active'))renderMarkets($('.filter.active')?.dataset.filter||'all');if($('#page-trade').classList.contains('active'))selectMarket(currentMarket);const now=Date.now();activeTrades.filter(t=>t.end<=now).forEach(t=>{const won=t.dir==='up'?t.market.price>=t.entry:t.market.price<=t.entry;if(won){const payout=t.amount*1.82;balance+=payout;showToast(`Demo trade settled: +${fmt(payout-t.amount)} USDT`)}else showToast(`Demo trade settled: -${fmt(t.amount)} USDT`)});activeTrades=activeTrades.filter(t=>t.end>now);updateBalances();renderPositions()},1000);
$$('.pledge-btn').forEach(b=>b.onclick=()=>{selectedPledge={product:b.dataset.product,min:Number(b.dataset.min)};$('#modal-title').textContent=`${selectedPledge.product} Pledge`;$('#pledge-amount').min=selectedPledge.min;$('#pledge-amount').value=selectedPledge.min;$('#pledge-modal').classList.add('open');$('#pledge-modal').setAttribute('aria-hidden','false')});function closeModal(){$('#pledge-modal').classList.remove('open');$('#pledge-modal').setAttribute('aria-hidden','true')}$('#modal-close').onclick=closeModal;$('#pledge-modal').onclick=e=>{if(e.target.id==='pledge-modal')closeModal()};$('#confirm-pledge').onclick=()=>{const amount=Number($('#pledge-amount').value);if(amount<selectedPledge.min)return showToast(`Minimum is ${fmt(selectedPledge.min)} USDT.`);if(amount>balance)return showToast('Insufficient demo balance.');balance-=amount;totalPledged+=amount;const row=document.createElement('div');row.className='pledge-row';row.innerHTML=`<span>${selectedPledge.product} Pledge</span><strong>${fmt(amount)} USDT</strong><span>Demo APY</span><span class="positive">Active</span>`;$('#pledge-list').appendChild(row);updateBalances();closeModal();showToast('Demo pledge added to portfolio.')};
function drawChart(){const canvas=$('#price-chart');if(!canvas)return;const rect=canvas.getBoundingClientRect();if(rect.width<10)return;const dpr=window.devicePixelRatio||1;canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;const ctx=canvas.getContext('2d');ctx.scale(dpr,dpr);const w=rect.width,h=rect.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='rgba(100,115,145,.14)';ctx.lineWidth=1;for(let i=1;i<7;i++){const y=h*i/7;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}for(let i=1;i<9;i++){const x=w*i/9;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}const n=Math.max(36,Math.floor(w/16)),data=[];let p=currentMarket.price*.97;for(let i=0;i<n;i++){const open=p;const close=open*(1+(Math.random()-.46)*.007);const high=Math.max(open,close)*(1+Math.random()*.003);const low=Math.min(open,close)*(1-Math.random()*.003);data.push({open,close,high,low});p=close}const scale=currentMarket.price/(data[data.length-1].close||1);data.forEach(d=>Object.keys(d).forEach(k=>d[k]*=scale));const min=Math.min(...data.map(d=>d.low))*.998,max=Math.max(...data.map(d=>d.high))*1.002;const y=v=>20+(max-v)/(max-min)*(h-40),step=w/n,cw=Math.max(3,step*.55);data.forEach((d,i)=>{const x=i*step+step/2,up=d.close>=d.open;ctx.strokeStyle=up?'#28c77c':'#ff5b67';ctx.fillStyle=ctx.strokeStyle;ctx.beginPath();ctx.moveTo(x,y(d.high));ctx.lineTo(x,y(d.low));ctx.stroke();ctx.fillRect(x-cw/2,Math.min(y(d.open),y(d.close)),cw,Math.max(2,Math.abs(y(d.close)-y(d.open))))})}
window.addEventListener('resize',()=>{if($('#page-trade').classList.contains('active'))drawChart()});renderMarkets();selectMarket(markets[0]);updatePotential();updateBalances();