const markets = [
  {symbol:'BTC/USDT',name:'Bitcoin',icon:'BTC',price:0,change:0,high:0,low:0,type:'crypto',bg:'#f7931a'},
  {symbol:'ETH/USDT',name:'Ethereum',icon:'ETH',price:0,change:0,high:0,low:0,type:'crypto',bg:'#627eea'},
  {symbol:'USDT/USDT',name:'Tether',icon:'USDT',price:1,change:0,high:1,low:1,type:'crypto',bg:'#34bd9d'},
  {symbol:'BNB/USDT',name:'BNB',icon:'BNB',price:0,change:0,high:0,low:0,type:'crypto',bg:'#c99b14'},
  {symbol:'SOL/USDT',name:'Solana',icon:'SOL',price:0,change:0,high:0,low:0,type:'crypto',bg:'#6d4cd8'},
  {symbol:'XRP/USDT',name:'XRP',icon:'XRP',price:0,change:0,high:0,low:0,type:'crypto',bg:'#111111'},
  {symbol:'DOGE/USDT',name:'Dogecoin',icon:'DOGE',price:0,change:0,high:0,low:0,type:'crypto',bg:'#9f842c'},
  {symbol:'ADA/USDT',name:'Cardano',icon:'ADA',price:0,change:0,high:0,low:0,type:'crypto',bg:'#3468d4'},
  {symbol:'AVAX/USDT',name:'Avalanche',icon:'AVAX',price:0,change:0,high:0,low:0,type:'crypto',bg:'#e84142'},
  {symbol:'LINK/USDT',name:'Chainlink',icon:'LINK',price:0,change:0,high:0,low:0,type:'crypto',bg:'#2a5ada'},
  {symbol:'LTC/USDT',name:'Litecoin',icon:'LTC',price:0,change:0,high:0,low:0,type:'crypto',bg:'#345d9d'}
]
window.markets=markets;
const demoSessionId=new URLSearchParams(location.search).get('demo');
const isDemoSession=Boolean(demoSessionId);
let currentMarket=markets[0],direction='up',duration=60,balance=isDemoSession?50000:0,totalPledged=0,activeTrades=[],selectedPledge={product:'Flexible',min:100};
const profitRates={30:21,60:29,90:37,180:45,360:53};
const minimumTradeAmounts={30:200,60:1000,90:10000,180:50000,360:250000};
const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);const fmt=(n,d=2)=>Number(n).toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d});
function decimals(v){return v<1?6:v<100?4:2}
function renderMarkets(filter='all'){const list=$('#market-list');list.innerHTML='';markets.filter(m=>filter==='all'||m.type===filter).forEach(m=>{const row=document.createElement('div');row.className='market-row';row.innerHTML=`<div class="market-name"><span class="coin-icon small">${tradeIconHTML(m)}</span><div><strong>${m.symbol}</strong><small class="muted" style="display:block;margin-top:3px">${m.name}</small></div></div><strong>${fmt(m.price,decimals(m.price))}</strong><strong class="${m.change>=0?'positive':'negative'}">${m.change>=0?'+':''}${m.change.toFixed(2)}%</strong><span>${fmt(m.high,decimals(m.high))}</span><button>Trade</button>`;row.querySelector('button').onclick=()=>{selectMarket(m);navigate('trade')};list.appendChild(row)})}
function selectMarket(m){if(!m)return;currentMarket=m;$('#trade-symbol').textContent=m.symbol;$('#trade-name').textContent=m.name;paintTradeIcon($('#trade-icon'),m);const valid=Number.isFinite(Number(m.price))&&Number(m.price)>0;$('#trade-price').textContent=valid?fmt(m.price,decimals(m.price)):'--';$('#trade-price').className=m.change>=0?'positive':'negative';$('#trade-change').textContent=valid?`${m.change>=0?'+':''}${Number(m.change||0).toFixed(2)}%`:'--';$('#trade-change').className=m.change>=0?'positive':'negative';$('#trade-high').textContent=valid&&Number(m.high)>0?fmt(m.high,decimals(m.high)):'--';$('#trade-low').textContent=valid&&Number(m.low)>0?fmt(m.low,decimals(m.low)):'--';const chartBadge=$('#chart-price-badge');if(chartBadge)chartBadge.textContent=valid?fmt(m.price,decimals(m.price)):'--';window.dispatchEvent(new CustomEvent('dapps:market-selected',{detail:{market:m}}))}
function navigate(name){if(!['home','markets','trade','pledge','assets'].includes(name))name='home';try{localStorage.setItem('dapps:lastPage',name)}catch{}const hash='#'+name;if(location.hash!==hash)history.replaceState(null,'',location.pathname+location.search+hash);$$('.page').forEach(p=>p.classList.remove('active'));const page=$(`#page-${name}`);if(page)page.classList.add('active');$$('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===name));window.scrollTo({top:0,behavior:'smooth'})}
const isMobileEntry=window.matchMedia?.('(max-width:760px)').matches===true;
const initialPage=isMobileEntry?'home':(location.hash.slice(1)||(()=>{try{return localStorage.getItem('dapps:lastPage')}catch{return null}})());
navigate(['home','markets','trade','pledge','assets'].includes(initialPage)?initialPage:'home');
$$('[data-nav]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.nav==='trade'){const btc=markets.find(m=>m.symbol==='BTC/USDT');if(btc)selectMarket(btc)}navigate(b.dataset.nav)}));$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderMarkets(b.dataset.filter)});
function currentProfitRate(){return profitRates[duration]??29}function currentMinimum(){return minimumTradeAmounts[duration]??1000}
function updatePotential(){const input=$('#trade-amount'),min=currentMinimum();input.min=min;input.placeholder=`Minimum ${fmt(min,0)} USDT`;const amount=Number(input.value)||0,rate=currentProfitRate(),profit=amount*rate/100,total=amount+profit;const r=$('#profit-rate'),p=$('#potential-profit');if(r)r.textContent=`+${rate}%`;if(p)p.textContent=`${fmt(profit)} USDT`;$('#potential-return').textContent=`${fmt(total)} USDT`}
$('#trade-amount').addEventListener('input',updatePotential);$$('[data-amount]').forEach(b=>b.onclick=()=>{$('#trade-amount').value=b.dataset.amount;updatePotential()});
$('#up-btn').onclick=()=>{direction='up';$('#up-btn').classList.add('active');$('#down-btn').classList.remove('active')};$('#down-btn').onclick=()=>{direction='down';$('#down-btn').classList.add('active');$('#up-btn').classList.remove('active')};$$('[data-duration]').forEach(b=>b.onclick=()=>{duration=Number(b.dataset.duration);$$('[data-duration]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const input=$('#trade-amount'),min=currentMinimum();input.min=min;if(!Number(input.value)||Number(input.value)<min)input.value=min;updatePotential()});
function showToast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(showToast.timer);showToast.timer=setTimeout(()=>t.classList.remove('show'),2600)}
$('#place-trade').onclick=()=>{const amount=Number($('#trade-amount').value),min=currentMinimum();if(!isDemoSession&&!localStorage.getItem('dapps:token'))return showToast('Sign in or start a simulation account to trade.');if(!amount||amount<min)return showToast(`Minimum for ${duration}s is ${fmt(min,0)} USDT.`);if(amount>balance)return showToast('Insufficient balance.');const rate=currentProfitRate();balance-=amount;activeTrades.push({id:Date.now(),market:currentMarket,dir:direction,entry:currentMarket.price,amount,duration,profitRate:rate,end:Date.now()+duration*1000});updateBalances();renderPositions();showToast(`${direction==='up'?'Up':'Down'} ${duration}s trade opened · +${rate}% profit.`)};
function renderPositions(){const list=$('#positions-list');if(!activeTrades.length){list.className='positions-list empty-state';list.textContent='No active trades yet.';return}list.className='positions-list';list.innerHTML=activeTrades.map(t=>{const left=Math.max(0,Math.ceil((t.end-Date.now())/1000));return `<div class="position-row"><strong>${t.market.symbol}</strong><span class="${t.dir==='up'?'positive':'negative'}">${t.dir==='up'?'↑ Up':'↓ Down'}</span><strong>${fmt(t.entry,decimals(t.entry))}</strong><span>${fmt(t.amount)} USDT · +${t.profitRate}%</span><span>${left}s</span><span>Active</span></div>`}).join('')}
function updateBalances(){
  const total=balance+Number(totalPledged||0);
  if($('#available-balance'))$('#available-balance').textContent=`${fmt(balance)} USDT`;
  if($('#asset-available'))$('#asset-available').textContent=fmt(balance);
  if($('#asset-pledged'))$('#asset-pledged').textContent=fmt(totalPledged);
  if($('#total-pledged'))$('#total-pledged').textContent=`${fmt(totalPledged)} USDT`;
  if($('#home-total-assets'))$('#home-total-assets').textContent=`$${fmt(total)}`;
  if($('#home-available'))$('#home-available').textContent=`$${fmt(balance)}`;
  const homeNote=document.querySelector('.asset-main small');if(homeNote){homeNote.textContent=isDemoSession?'Simulation balance · resets with a new simulation session':localStorage.getItem('dapps:token')?'Account balance':'No funds available';homeNote.className=isDemoSession?'positive':'muted'}
  const assetTotal=document.querySelector('#page-assets .balance-card:first-child strong');if(assetTotal)assetTotal.textContent=`$${fmt(total)}`;
  const assetApprox=document.querySelector('#page-assets .balance-card:first-child small');if(assetApprox)assetApprox.textContent=`≈ ${fmt(total)} USDT`;
  const assetRow=document.querySelector('#page-assets .asset-row');if(assetRow){const vals=assetRow.children;if(vals[1])vals[1].textContent=fmt(total);if(vals[2])vals[2].textContent=fmt(balance);if(vals[3])vals[3].textContent=fmt(totalPledged)}
}
$$('.pledge-btn').forEach(b=>b.onclick=()=>{selectedPledge={product:b.dataset.product,min:Number(b.dataset.min)};$('#modal-title').textContent=`${selectedPledge.product} Pledge`;$('#pledge-amount').min=selectedPledge.min;$('#pledge-amount').value=selectedPledge.min;$('#pledge-modal').classList.add('open');$('#pledge-modal').setAttribute('aria-hidden','false')});function closeModal(){$('#pledge-modal').classList.remove('open');$('#pledge-modal').setAttribute('aria-hidden','true')}$('#modal-close').onclick=closeModal;$('#pledge-modal').onclick=e=>{if(e.target.id==='pledge-modal')closeModal()};$('#confirm-pledge').onclick=()=>{const amount=Number($('#pledge-amount').value);if(!isDemoSession&&!localStorage.getItem('dapps:token'))return showToast('Sign in or start a simulation account first.');if(amount<selectedPledge.min)return showToast(`Minimum is ${fmt(selectedPledge.min)} USDT.`);if(amount>balance)return showToast('Insufficient balance.');balance-=amount;totalPledged+=amount;const row=document.createElement('div');row.className='pledge-row';row.innerHTML=`<span>${selectedPledge.product} Pledge</span><strong>${fmt(amount)} USDT</strong><span>Demo APY</span><span class="positive">Active</span>`;$('#pledge-list').appendChild(row);updateBalances();closeModal();showToast('Pledge added to portfolio.')};
setInterval(()=>{const now=Date.now();if($('#page-markets').classList.contains('active'))renderMarkets($('.filter.active')?.dataset.filter||'all');if($('#page-trade').classList.contains('active')){$('#trade-price').textContent=window.__publicQuoteFresh?.(currentMarket)===false?'--':fmt(currentMarket.price,decimals(currentMarket.price));$('#trade-high').textContent=fmt(currentMarket.high,decimals(currentMarket.high));$('#trade-low').textContent=fmt(currentMarket.low,decimals(currentMarket.low));{const chartBadge=$('#chart-price-badge');if(chartBadge)chartBadge.textContent=fmt(currentMarket.price,decimals(currentMarket.price))}}activeTrades.filter(t=>t.end<=now).forEach(t=>{const won=t.dir==='up'?t.market.price>=t.entry:t.market.price<=t.entry;if(won){const payout=t.amount*(1+t.profitRate/100);balance+=payout;showToast(`Trade settled: +${fmt(t.amount*t.profitRate/100)} USDT (${t.profitRate}%)`)}else showToast(`Trade settled: -${fmt(t.amount)} USDT`)});activeTrades=activeTrades.filter(t=>t.end>now);updateBalances();renderPositions()},1000);
renderMarkets();selectMarket(markets[0]);updatePotential();updateBalances();