(() => {
  const API=localStorage.getItem('dapps:apiBase')||'https://dapps-trading-platform-production.up.railway.app';
  const token=localStorage.getItem('dapps:token');
  const demoId=new URLSearchParams(location.search).get('demo');
  const demoMode=Boolean(demoId);
  const suffix=demoMode?':'+demoId:'';
  const ACTIVE_KEY='dapps:activeTrades:v3'+suffix;
  const HISTORY_KEY='dapps:tradeHistory:v3'+suffix;
  const BALANCE_KEY='dapps:demoBalance:v3'+suffix;
  const minimums={30:200,60:1000,90:10000,180:50000,360:250000};
  const rates={30:21,60:29,90:37,180:45,360:53};
  const placeBtn=document.querySelector('#place-trade');
  const amountInput=document.querySelector('#trade-amount');
  const list=document.querySelector('#positions-list');
  const head=document.querySelector('.positions-table-head');
  const tabs=[...document.querySelectorAll('.positions-heading .tab-row button')];
  if(!placeBtn||!amountInput||!list||!head)return;

  const style=document.createElement('style');
  style.textContent=`
  .positions-table-head,.position-row{grid-template-columns:1.05fr .75fr 1fr 1fr 1.15fr .8fr .85fr;align-items:center}
  .position-row.history-clickable{cursor:pointer;transition:background .18s ease}.position-row.history-clickable:hover,.position-row.history-clickable:focus{background:rgba(31,112,255,.08);outline:none}
  .status-pill{display:inline-flex;padding:5px 8px;border-radius:999px;font-weight:700;font-size:10px}.status-pill.active{background:rgba(77,124,255,.12);color:#8facff}.status-pill.won{background:rgba(40,199,124,.12);color:#62dca0}.status-pill.lost{background:rgba(255,91,103,.12);color:#ff8b94}.trade-time{color:#a8b2c7;white-space:nowrap}.countdown{font-variant-numeric:tabular-nums;font-weight:700}
  .trade-dialog-backdrop{position:fixed;inset:0;z-index:1000;background:rgba(2,8,16,.68);backdrop-filter:blur(7px);display:grid;place-items:center;padding:20px}.trade-dialog{width:min(92vw,410px);border:1px solid #29415d;border-radius:22px;background:linear-gradient(180deg,#0d1c2f,#081421);box-shadow:0 28px 80px rgba(0,0,0,.55);padding:24px;color:#f5f8fc}.trade-dialog-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}.trade-dialog-head strong{font-size:17px}.trade-dialog-head span{font-size:11px;color:#8fa4bb}
  .trade-count-ring{width:142px;height:142px;margin:8px auto 18px;border-radius:50%;display:grid;place-items:center;position:relative;background:conic-gradient(#218cff var(--progress),#172a40 0);box-shadow:0 0 34px rgba(33,140,255,.16)}.trade-count-ring:after{content:"";position:absolute;inset:7px;border-radius:50%;background:#0a1727}.trade-count-ring>div{position:relative;z-index:1;text-align:center}.trade-count-ring b{display:block;font-size:42px;font-variant-numeric:tabular-nums}.trade-count-ring small{color:#8fa4bb}
  .live-pnl{margin:0 0 14px;padding:14px 15px;border:1px solid #29415d;border-radius:14px;background:#0d1e31}.live-pnl-top{display:flex;justify-content:space-between;gap:14px;align-items:flex-end}.live-pnl span{font-size:10px;color:#8fa4bb}.live-pnl strong{font-size:20px}.live-pnl .live-price{text-align:right}.live-pnl .live-price b{display:block;font-size:14px}.live-pnl .live-move{font-size:11px;margin-top:3px;display:block}.live-pnl-note{margin-top:9px;font-size:10px;color:#7890aa;line-height:1.4}
  .trade-dialog-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.trade-dialog-cell{padding:11px 12px;border-radius:12px;background:#0f2034;border:1px solid #203750}.trade-dialog-cell span{display:block;font-size:10px;color:#8fa4bb;margin-bottom:5px}.trade-dialog-cell b{font-size:13px}.trade-dialog-note{text-align:center;color:#8fa4bb;font-size:11px;margin-top:16px}.trade-result-icon{width:68px;height:68px;border-radius:50%;margin:2px auto 14px;display:grid;place-items:center;font-size:30px;font-weight:900}.trade-result-icon.won{background:rgba(0,229,160,.12);color:#00e5a0;border:1px solid rgba(0,229,160,.35)}.trade-result-icon.lost{background:rgba(255,99,112,.12);color:#ff6370;border:1px solid rgba(255,99,112,.35)}.trade-result-title{text-align:center;font-size:25px;margin:0 0 4px}.trade-result-pnl{text-align:center;font-size:21px;font-weight:800;margin:0 0 20px}.trade-result-pnl.won{color:#00e5a0}.trade-result-pnl.lost{color:#ff6370}.trade-dialog-close{width:100%;margin-top:18px;border:0;border-radius:12px;padding:13px;background:linear-gradient(135deg,#1688ff,#4478ff);color:#fff;font-weight:800}
  @media(max-width:720px){.positions-panel{overflow-x:auto}.positions-table-head,.position-row{display:grid!important;grid-template-columns:120px 90px 110px 110px 155px 90px 85px;min-width:760px;padding:12px 14px}.trade-dialog{padding:20px}.trade-count-ring{width:130px;height:130px}}
  `;
  document.head.appendChild(style);

  const fmtTime=ts=>new Date(ts).toLocaleString('en-US',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false});
  let backendTrades=[],mode='active',settling=new Set(),dialogTradeNo=null,dialogTimer=null;
  const authHeaders=()=>({'content-type':'application/json',Authorization:'Bearer '+token});
  async function api(path,options={}){const r=await fetch(API+path,{...options,headers:{...authHeaders(),...(options.headers||{})}});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'Request failed');return d}
  function marketBySymbol(symbol){return markets.find(m=>m.symbol===symbol)||currentMarket}
  function closeDialog(){document.querySelector('.trade-dialog-backdrop')?.remove();if(dialogTimer)clearInterval(dialogTimer);dialogTimer=null;dialogTradeNo=null}
  function liveEstimate(t){const m=marketBySymbol(t.symbol),price=Number(m?.price||t.entryPrice),entry=Number(t.entryPrice),amount=Number(t.amount),rate=Number(t.profitRate||rates[t.duration]||0);const movePct=entry?((price-entry)/entry)*100:0;const itm=t.direction==='up'?price>entry:price<entry;const flat=Math.abs(price-entry)<Math.max(Math.abs(entry)*1e-9,1e-12);const est=flat?0:(itm?amount*rate/100:-amount);return{price,movePct,est,itm,flat}}
  function countdownDialog(t){
    closeDialog();dialogTradeNo=t.tradeNo;
    const start=new Date(t.openedAt).getTime(),end=new Date(t.expiresAt).getTime(),durationMs=Math.max(1,end-start);
    const overlay=document.createElement('div');overlay.className='trade-dialog-backdrop';
    overlay.innerHTML=`<div class="trade-dialog"><div class="trade-dialog-head"><strong>Trade in Progress</strong><span>${t.symbol}</span></div><div class="trade-count-ring" style="--progress:100%"><div><b data-seconds>--</b><small>seconds remaining</small></div></div><div class="live-pnl"><div class="live-pnl-top"><div><span>Estimated P/L</span><strong data-live-pnl>0.00 USDT</strong></div><div class="live-price"><span>Current Market</span><b data-live-price>--</b><small class="live-move" data-live-move>0.00%</small></div></div><div class="live-pnl-note">Estimate follows the current market trend and can change until settlement. Final result is determined at expiry.</div></div><div class="trade-dialog-grid"><div class="trade-dialog-cell"><span>Direction</span><b class="${t.direction==='up'?'positive':'negative'}">${t.direction==='up'?'↑ Up':'↓ Down'}</b></div><div class="trade-dialog-cell"><span>Amount</span><b>${fmt(t.amount)} USDT</b></div><div class="trade-dialog-cell"><span>Entry Price</span><b>${fmt(t.entryPrice,decimals(t.entryPrice))}</b></div><div class="trade-dialog-cell"><span>Duration</span><b>${t.duration}s</b></div></div><div class="trade-dialog-note">The settlement detail will appear automatically when the countdown ends.</div></div>`;
    document.body.appendChild(overlay);
    const tick=()=>{if(!document.body.contains(overlay))return;const left=Math.max(0,end-Date.now()),seconds=Math.ceil(left/1000),progress=Math.max(0,Math.min(100,left/durationMs*100));overlay.querySelector('[data-seconds]').textContent=seconds;overlay.querySelector('.trade-count-ring').style.setProperty('--progress',progress+'%');const e=liveEstimate(t),p=overlay.querySelector('[data-live-pnl]'),price=overlay.querySelector('[data-live-price]'),mv=overlay.querySelector('[data-live-move]');p.textContent=`${e.est>0?'+':''}${fmt(e.est)} USDT`;p.className=e.est>0?'positive':e.est<0?'negative':'muted';price.textContent=fmt(e.price,decimals(e.price));mv.textContent=`${e.movePct>=0?'+':''}${e.movePct.toFixed(3)}%`;mv.className='live-move '+(e.movePct>=0?'positive':'negative');if(left<=0&&dialogTimer){clearInterval(dialogTimer);dialogTimer=null}};
    tick();dialogTimer=setInterval(tick,200);
  }
  function resultDialog(t){closeDialog();const won=t.result==='won',pnl=Number(t.profitAmount||0);const overlay=document.createElement('div');overlay.className='trade-dialog-backdrop';overlay.innerHTML=`<div class="trade-dialog"><div class="trade-result-icon ${won?'won':'lost'}">${won?'✓':'−'}</div><h3 class="trade-result-title">${won?'Trade Won':'Trade Closed'}</h3><div class="trade-result-pnl ${won?'won':'lost'}">${pnl>0?'+':''}${fmt(pnl)} USDT</div><div class="trade-dialog-grid"><div class="trade-dialog-cell"><span>Market</span><b>${t.symbol}</b></div><div class="trade-dialog-cell"><span>Direction</span><b>${t.direction==='up'?'↑ Up':'↓ Down'}</b></div><div class="trade-dialog-cell"><span>Entry Price</span><b>${fmt(t.entryPrice,decimals(t.entryPrice))}</b></div><div class="trade-dialog-cell"><span>Exit Price</span><b>${fmt(t.exitPrice||0,decimals(t.exitPrice||t.entryPrice))}</b></div><div class="trade-dialog-cell"><span>Amount</span><b>${fmt(t.amount)} USDT</b></div><div class="trade-dialog-cell"><span>Duration</span><b>${t.duration}s</b></div><div class="trade-dialog-cell"><span>Opened</span><b>${fmtTime(t.openedAt)}</b></div><div class="trade-dialog-cell"><span>Closed</span><b>${fmtTime(t.settledAt||Date.now())}</b></div></div><button class="trade-dialog-close">Done</button></div>`;document.body.appendChild(overlay);overlay.querySelector('.trade-dialog-close').onclick=closeDialog}
  function syncLegacySnapshot(){try{const active=backendTrades.filter(t=>t.result==='pending').map(t=>({id:t.tradeNo,symbol:t.symbol,name:t.symbol,dir:t.direction,entry:t.entryPrice,amount:t.amount,duration:t.duration,profitRate:t.profitRate,openedAt:new Date(t.openedAt).getTime(),endAt:new Date(t.expiresAt).getTime(),status:'active'}));const history=backendTrades.filter(t=>t.result!=='pending').map(t=>({id:t.tradeNo,symbol:t.symbol,name:t.symbol,dir:t.direction,entry:t.entryPrice,exit:t.exitPrice,amount:t.amount,duration:t.duration,profitRate:t.profitRate,openedAt:new Date(t.openedAt).getTime(),closedAt:new Date(t.settledAt).getTime(),status:'closed',result:t.result==='won'?'won':'lost',profit:t.profitAmount}));localStorage.setItem('dapps:activeTrades:v2',JSON.stringify(active));localStorage.setItem('dapps:tradeHistory:v2',JSON.stringify(history))}catch{}}
  async function refreshWallet(){try{const d=await api('/api/wallet');balance=Number(d.balance.available)||0;updateBalances()}catch(e){if(!e.message.includes('Authentication'))console.warn(e)}}
  async function refreshTrades(){try{const d=await api('/api/trades');backendTrades=d.trades||[];syncLegacySnapshot();renderLedger()}catch(e){showToast(e.message)}}
  function renderActive(){const rows=backendTrades.filter(t=>t.result==='pending');head.innerHTML='<span>Pair</span><span>Direction</span><span>Entry</span><span>Amount</span><span>Opened</span><span>Time Left</span><span>Status</span>';if(!rows.length){list.className='positions-list empty-state';list.textContent='No active trades.';return}const now=Date.now();list.className='positions-list';list.innerHTML=rows.map(t=>`<div class="position-row"><strong>${t.symbol}</strong><span class="${t.direction==='up'?'positive':'negative'}">${t.direction==='up'?'↑ Up':'↓ Down'}</span><strong>${fmt(t.entryPrice,decimals(t.entryPrice))}</strong><span>${fmt(t.amount)} USDT</span><span class="trade-time">${fmtTime(t.openedAt)}</span><span class="countdown">${Math.max(0,Math.ceil((new Date(t.expiresAt).getTime()-now)/1000))}s</span><span><i class="status-pill active">Trading</i></span></div>`).join('')}
  function renderHistory(){const rows=backendTrades.filter(t=>t.result!=='pending');head.innerHTML='<span>Pair</span><span>Result</span><span>Entry</span><span>Exit</span><span>Amount</span><span>Opened</span><span>Closed</span>';if(!rows.length){list.className='positions-list empty-state';list.textContent='No completed trades yet.';return}list.className='positions-list';list.innerHTML=rows.map((t,i)=>`<div class="position-row history-clickable" tabindex="0" data-history-index="${i}" title="View trade details"><strong>${t.symbol}</strong><span><i class="status-pill ${t.result==='won'?'won':'lost'}">${t.result==='won'?'Won':'Lost'}</i></span><strong>${fmt(t.entryPrice,decimals(t.entryPrice))}</strong><strong>${fmt(t.exitPrice||0,decimals(t.exitPrice||t.entryPrice))}</strong><span>${fmt(t.amount)} USDT</span><span class="trade-time">${fmtTime(t.openedAt)}</span><span class="trade-time">${fmtTime(t.settledAt)}</span></div>`).join('');list.querySelectorAll('[data-history-index]').forEach(el=>{const open=()=>resultDialog(rows[Number(el.dataset.historyIndex)]);el.onclick=open;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}})}
  function renderLedger(){mode==='history'?renderHistory():renderActive()}window.renderPositions=renderLedger;
  tabs.forEach((tab,index)=>tab.addEventListener('click',()=>{mode=index===0?'active':'history';tabs.forEach(x=>x.classList.remove('active'));tab.classList.add('active');head.style.display='grid';renderLedger()}));

  if(token&&!demoMode){
    activeTrades.length=0;
    placeBtn.onclick=async()=>{const amount=Number(amountInput.value)||0,min=minimums[Number(duration)]??1000;if(amount<min)return showToast(`Order blocked: minimum for ${duration}s is ${fmt(min,0)} USDT.`);placeBtn.disabled=true;try{const d=await api('/api/trades',{method:'POST',body:JSON.stringify({symbol:currentMarket.symbol,direction,duration:Number(duration),amount,entryPrice:Number(currentMarket.price)})});balance=Number(d.balance.available);updateBalances();mode='active';tabs.forEach((x,i)=>x.classList.toggle('active',i===0));await refreshTrades();const opened=backendTrades.find(t=>t.tradeNo===d.trade.tradeNo)||d.trade;countdownDialog(opened)}catch(e){showToast(e.message)}finally{placeBtn.disabled=false}};
    async function autoSettle(){for(const t of backendTrades.filter(x=>x.result==='pending'&&new Date(x.expiresAt).getTime()<=Date.now())){if(settling.has(t.tradeNo))continue;settling.add(t.tradeNo);try{const m=marketBySymbol(t.symbol);const d=await api('/api/trades/'+encodeURIComponent(t.tradeNo)+'/settle',{method:'POST',body:JSON.stringify({exitPrice:Number(m.price)})});balance=Number(d.balance.available);updateBalances();if(dialogTradeNo===t.tradeNo)resultDialog(d.trade)}catch(e){if(!e.message.includes('not expired'))console.warn(e)}finally{settling.delete(t.tradeNo)}}if(backendTrades.some(x=>x.result==='pending'&&new Date(x.expiresAt).getTime()<=Date.now()))await refreshTrades();else if(mode==='active')renderActive()}
    Promise.all([refreshWallet(),refreshTrades()]);setInterval(autoSettle,1000);setInterval(refreshTrades,10000);
  }else{
    if(!demoMode){balance=0;backendTrades=[];renderLedger();updateBalances();placeBtn.onclick=()=>showToast('Start a Simulation Account from registration or sign in to trade.');return}
    const store=sessionStorage;let ledgerActive=[],ledgerHistory=[];
    try{ledgerActive=JSON.parse(store.getItem(ACTIVE_KEY)||'[]');ledgerHistory=JSON.parse(store.getItem(HISTORY_KEY)||'[]')}catch{}
    const saved=Number(store.getItem(BALANCE_KEY));balance=Number.isFinite(saved)?saved:50000;
    const save=()=>{store.setItem(ACTIVE_KEY,JSON.stringify(ledgerActive));store.setItem(HISTORY_KEY,JSON.stringify(ledgerHistory));store.setItem(BALANCE_KEY,String(balance))};if(!store.getItem(BALANCE_KEY))save();
    const rebuild=()=>{backendTrades=[...ledgerActive.map(t=>({tradeNo:t.id,symbol:t.symbol,direction:t.dir,duration:t.duration,amount:t.amount,profitRate:t.profitRate,entryPrice:t.entry,result:'pending',openedAt:new Date(t.openedAt),expiresAt:new Date(t.endAt)})),...ledgerHistory.map(t=>({tradeNo:t.id,symbol:t.symbol,direction:t.dir,duration:t.duration,amount:t.amount,profitRate:t.profitRate,entryPrice:t.entry,exitPrice:t.exit,result:t.result==='won'?'won':'lost',profitAmount:t.profit,openedAt:new Date(t.openedAt),settledAt:new Date(t.closedAt)}))]};rebuild();
    placeBtn.onclick=()=>{const amount=Number(amountInput.value)||0,min=minimums[Number(duration)]??1000,rate=rates[Number(duration)]??29;if(amount<min)return showToast(`Order blocked: minimum for ${duration}s is ${fmt(min,0)} USDT.`);if(amount>balance)return showToast('Order blocked: insufficient simulation balance.');const now=Date.now(),t={id:String(now),symbol:currentMarket.symbol,dir:direction,entry:currentMarket.price,amount,duration:Number(duration),profitRate:rate,openedAt:now,endAt:now+Number(duration)*1000};balance-=amount;ledgerActive.unshift(t);save();rebuild();updateBalances();renderLedger();countdownDialog(backendTrades[0])};
    setInterval(()=>{const now=Date.now(),keep=[];let changed=false;ledgerActive.forEach(t=>{if(t.endAt>now){keep.push(t);return}const m=marketBySymbol(t.symbol),won=t.dir==='up'?m.price>=t.entry:m.price<=t.entry,profit=won?t.amount*t.profitRate/100:-t.amount;if(won)balance+=t.amount+profit;const closed={...t,exit:m.price,closedAt:now,result:won?'won':'lost',profit};ledgerHistory.unshift(closed);if(dialogTradeNo===t.id)resultDialog({tradeNo:t.id,symbol:t.symbol,direction:t.dir,duration:t.duration,amount:t.amount,profitRate:t.profitRate,entryPrice:t.entry,exitPrice:m.price,result:won?'won':'lost',profitAmount:profit,openedAt:new Date(t.openedAt),settledAt:new Date(now)});changed=true});if(changed){ledgerActive=keep;save();rebuild();updateBalances();renderLedger()}else if(mode==='active')renderActive()},1000);renderLedger();updateBalances();
  }
})();